name: Generate Local Stats

on:
  schedule:
    - cron: "0 */12 * * *" # Atualiza a cada 12 horas
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v1
        with:
          card: stats
          options: username=Shin-ZeroSeven&show_icons=true&hide_border=true&bg_color=0A0A0A&title_color=08F7FE&text_color=A0A0A0&icon_color=FF003C&border_color=08F7FE
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=Shin-ZeroSeven&layout=compact&hide_border=true&bg_color=0A0A0A&title_color=08F7FE&text_color=A0A0A0&border_color=08F7FE
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add stats.svg top-langs.svg
          git commit -m "Atualizando HUD Stats" || exit 0
          git push
